#!/bin/sh
QDIR=..
rm -f $QDIR/libs/sqlite3-*/ext/sqlite3/*.o
rm -f $QDIR/libs/sqlite3-*/ext/sqlite3/*.log
rmdir $QDIR/libs/sqlite3-*/ext/sqlite3
rmdir $QDIR/libs/sqlite3-*/ext
rmdir $QDIR/libs/sqlite3-*
cp $QDIR/.ruby-version /tmp
SQL_DIR=$( echo $QDIR/libs/sqlite3-* )
if echo $SQL_DIR | grep -qv "^/"; then
  SQL_DIR="$( pwd )/$SQL_DIR"
fi
cd "$SQL_DIR"
echo $SQL_DIR - $( pwd )

# This is in case we have spaces in the pathname...
cp -a . /tmp/sqlite3
cd /tmp/sqlite3
mv ../.ruby-version .

rm -f ext/sqlite3/*.o
#ruby setup.rb config --prefix=/usr &&
ruby setup.rb config &&
ruby setup.rb setup &&
sudo ruby setup.rb install
if false; then
if which sudo; then
  sudo ruby setup.rb install
else
  ruby setup.rb install --install-prefix=/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/
fi
fi

# Again, if we had spaces
cp ext/sqlite3/*.o "$SQL_DIR/ext/sqlite3"
cd "$SQL_DIR"
#rm -rf /tmp/sqlite3
